INSERT INTO ROLES VALUES(1, 'USER');

INSERT INTO INGREDIENTS VALUES(1, 'Onion');
INSERT INTO INGREDIENTS VALUES(2, 'Green Onion');
INSERT INTO INGREDIENTS VALUES(3, 'Bok Choy');
INSERT INTO INGREDIENTS VALUES(4, 'Olive');
INSERT INTO INGREDIENTS VALUES(5, 'Olive Oil');
INSERT INTO INGREDIENTS VALUES(6, 'Sesame Oil');
INSERT INTO INGREDIENTS VALUES(7, 'Chicken');
INSERT INTO INGREDIENTS VALUES(8, 'Egg');
INSERT INTO INGREDIENTS VALUES(9, 'Rice');
INSERT INTO INGREDIENTS VALUES(10, 'Salt');
INSERT INTO INGREDIENTS VALUES(11, 'Sugar');
INSERT INTO INGREDIENTS VALUES(12, 'Butter');
INSERT INTO INGREDIENTS VALUES(13, 'Celery');
INSERT INTO INGREDIENTS VALUES(14, 'Carrot');
